// <auto-generated />
using System;
using BauDoku.Sync.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BauDoku.Sync.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SyncDbContext))]
    [Migration("20260210183051_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BauDoku.Sync.Domain.Aggregates.SyncBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("device_id");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.HasKey("Id");

                    b.ToTable("sync_batches", (string)null);
                });

            modelBuilder.Entity("BauDoku.Sync.Domain.Entities.ConflictRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_payload");

                    b.Property<long>("ClientVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("client_version");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedPayload")
                        .HasColumnType("text")
                        .HasColumnName("resolved_payload");

                    b.Property<string>("ServerPayload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("server_payload");

                    b.Property<long>("ServerVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("server_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("sync_batch_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("sync_batch_id");

                    b.ToTable("sync_conflicts", (string)null);
                });

            modelBuilder.Entity("BauDoku.Sync.Domain.Entities.SyncDelta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("BaseVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("base_version");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("operation");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<long>("ServerVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("server_version");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<Guid>("sync_batch_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("sync_batch_id");

                    b.ToTable("sync_deltas", (string)null);
                });

            modelBuilder.Entity("BauDoku.Sync.Infrastructure.Persistence.EntityVersionEntry", b =>
                {
                    b.Property<string>("EntityType")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("entity_type");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("LastDeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_device_id");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("EntityType", "EntityId");

                    b.HasIndex("LastModified")
                        .HasDatabaseName("ix_entity_versions_last_modified");

                    b.ToTable("entity_versions", (string)null);
                });

            modelBuilder.Entity("BauDoku.Sync.Domain.Entities.ConflictRecord", b =>
                {
                    b.HasOne("BauDoku.Sync.Domain.Aggregates.SyncBatch", null)
                        .WithMany("Conflicts")
                        .HasForeignKey("sync_batch_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BauDoku.Sync.Domain.ValueObjects.EntityReference", "EntityRef", b1 =>
                        {
                            b1.Property<Guid>("ConflictRecordId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("entity_id");

                            b1.Property<string>("EntityType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("entity_type");

                            b1.HasKey("ConflictRecordId");

                            b1.ToTable("sync_conflicts");

                            b1.WithOwner()
                                .HasForeignKey("ConflictRecordId");
                        });

                    b.Navigation("EntityRef")
                        .IsRequired();
                });

            modelBuilder.Entity("BauDoku.Sync.Domain.Entities.SyncDelta", b =>
                {
                    b.HasOne("BauDoku.Sync.Domain.Aggregates.SyncBatch", null)
                        .WithMany("Deltas")
                        .HasForeignKey("sync_batch_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BauDoku.Sync.Domain.ValueObjects.EntityReference", "EntityRef", b1 =>
                        {
                            b1.Property<Guid>("SyncDeltaId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("EntityId")
                                .HasColumnType("uuid")
                                .HasColumnName("entity_id");

                            b1.Property<string>("EntityType")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("entity_type");

                            b1.HasKey("SyncDeltaId");

                            b1.ToTable("sync_deltas");

                            b1.WithOwner()
                                .HasForeignKey("SyncDeltaId");
                        });

                    b.Navigation("EntityRef")
                        .IsRequired();
                });

            modelBuilder.Entity("BauDoku.Sync.Domain.Aggregates.SyncBatch", b =>
                {
                    b.Navigation("Conflicts");

                    b.Navigation("Deltas");
                });
#pragma warning restore 612, 618
        }
    }
}
