// <auto-generated />
using System;
using BauDoku.Documentation.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BauDoku.Documentation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DocumentationDbContext))]
    [Migration("20260213184904_AddIndexesAndDecimalCrossSection")]
    partial class AddIndexesAndDecimalCrossSection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BauDoku.Documentation.Domain.Aggregates.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth_mm");

                    b.Property<Point>("Location")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("geometry(Point, 4326)")
                        .HasColumnName("location")
                        .HasComputedColumnSql("ST_SetSRID(ST_MakePoint(gps_longitude, gps_latitude), 4326)", true);

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("ModelName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("QualityGrade")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("gps_quality_grade");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_installations_project_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_installations_status");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_installations_zone_id");

                    b.ToTable("installations", (string)null);
                });

            modelBuilder.Entity("BauDoku.Documentation.Domain.Entities.Measurement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measured_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("result");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.ToTable("measurements", (string)null);
                });

            modelBuilder.Entity("BauDoku.Documentation.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("blob_url");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid")
                        .HasColumnName("installation_id");

                    b.Property<string>("PhotoType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("photo_type");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.ToTable("photos", (string)null);
                });

            modelBuilder.Entity("BauDoku.Documentation.Domain.Aggregates.Installation", b =>
                {
                    b.OwnsOne("BauDoku.Documentation.Domain.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("InstallationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("description");

                            b1.HasKey("InstallationId");

                            b1.ToTable("installations");

                            b1.WithOwner()
                                .HasForeignKey("InstallationId");
                        });

                    b.OwnsOne("BauDoku.Documentation.Domain.ValueObjects.GpsPosition", "Position", b1 =>
                        {
                            b1.Property<Guid>("InstallationId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("Altitude")
                                .HasColumnType("double precision")
                                .HasColumnName("gps_altitude");

                            b1.Property<double?>("CorrectionAge")
                                .HasColumnType("double precision")
                                .HasColumnName("gps_correction_age");

                            b1.Property<string>("CorrectionService")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("gps_correction_service");

                            b1.Property<double?>("Hdop")
                                .HasColumnType("double precision")
                                .HasColumnName("gps_hdop");

                            b1.Property<double>("HorizontalAccuracy")
                                .HasColumnType("double precision")
                                .HasColumnName("gps_horizontal_accuracy");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("gps_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("gps_longitude");

                            b1.Property<string>("RtkFixStatus")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("gps_rtk_fix_status");

                            b1.Property<int?>("SatelliteCount")
                                .HasColumnType("integer")
                                .HasColumnName("gps_satellite_count");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("gps_source");

                            b1.HasKey("InstallationId");

                            b1.ToTable("installations");

                            b1.WithOwner()
                                .HasForeignKey("InstallationId");
                        });

                    b.OwnsOne("BauDoku.Documentation.Domain.ValueObjects.CableSpec", "CableSpec", b1 =>
                        {
                            b1.Property<Guid>("InstallationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CableType")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("cable_type");

                            b1.Property<string>("Color")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("cable_color");

                            b1.Property<int?>("ConductorCount")
                                .HasColumnType("integer")
                                .HasColumnName("cable_conductor_count");

                            b1.Property<decimal?>("CrossSection")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("cable_cross_section");

                            b1.HasKey("InstallationId");

                            b1.ToTable("installations");

                            b1.WithOwner()
                                .HasForeignKey("InstallationId");
                        });

                    b.Navigation("CableSpec");

                    b.Navigation("Description");

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("BauDoku.Documentation.Domain.Entities.Measurement", b =>
                {
                    b.HasOne("BauDoku.Documentation.Domain.Aggregates.Installation", null)
                        .WithMany("Measurements")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BauDoku.Documentation.Domain.ValueObjects.MeasurementValue", "Value", b1 =>
                        {
                            b1.Property<Guid>("MeasurementId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("MaxThreshold")
                                .HasColumnType("double precision")
                                .HasColumnName("max_threshold");

                            b1.Property<double?>("MinThreshold")
                                .HasColumnType("double precision")
                                .HasColumnName("min_threshold");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("measurement_unit");

                            b1.Property<double>("Value")
                                .HasColumnType("double precision")
                                .HasColumnName("measurement_value");

                            b1.HasKey("MeasurementId");

                            b1.ToTable("measurements");

                            b1.WithOwner()
                                .HasForeignKey("MeasurementId");
                        });

                    b.Navigation("Value")
                        .IsRequired();
                });

            modelBuilder.Entity("BauDoku.Documentation.Domain.Entities.Photo", b =>
                {
                    b.HasOne("BauDoku.Documentation.Domain.Aggregates.Installation", null)
                        .WithMany("Photos")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BauDoku.Documentation.Domain.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("PhotoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("description");

                            b1.HasKey("PhotoId");

                            b1.ToTable("photos");

                            b1.WithOwner()
                                .HasForeignKey("PhotoId");
                        });

                    b.OwnsOne("BauDoku.Documentation.Domain.ValueObjects.GpsPosition", "Position", b1 =>
                        {
                            b1.Property<Guid>("PhotoId")
                                .HasColumnType("uuid");

                            b1.Property<double?>("Altitude")
                                .HasColumnType("double precision")
                                .HasColumnName("gps_altitude");

                            b1.Property<double?>("CorrectionAge")
                                .HasColumnType("double precision")
                                .HasColumnName("gps_correction_age");

                            b1.Property<string>("CorrectionService")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("gps_correction_service");

                            b1.Property<double?>("Hdop")
                                .HasColumnType("double precision")
                                .HasColumnName("gps_hdop");

                            b1.Property<double>("HorizontalAccuracy")
                                .HasColumnType("double precision")
                                .HasColumnName("gps_horizontal_accuracy");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("gps_latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("gps_longitude");

                            b1.Property<string>("RtkFixStatus")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("gps_rtk_fix_status");

                            b1.Property<int?>("SatelliteCount")
                                .HasColumnType("integer")
                                .HasColumnName("gps_satellite_count");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("gps_source");

                            b1.HasKey("PhotoId");

                            b1.ToTable("photos");

                            b1.WithOwner()
                                .HasForeignKey("PhotoId");
                        });

                    b.OwnsOne("BauDoku.Documentation.Domain.ValueObjects.Caption", "Caption", b1 =>
                        {
                            b1.Property<Guid>("PhotoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("caption");

                            b1.HasKey("PhotoId");

                            b1.ToTable("photos");

                            b1.WithOwner()
                                .HasForeignKey("PhotoId");
                        });

                    b.Navigation("Caption");

                    b.Navigation("Description");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("BauDoku.Documentation.Domain.Aggregates.Installation", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
