// <auto-generated />
using System;
using BauDoku.Documentation.Infrastructure.ReadModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BauDoku.Documentation.Infrastructure.ReadModel.Migrations
{
    [DbContext(typeof(ReadModelDbContext))]
    partial class ReadModelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("documentation_read")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BauDoku.Documentation.Infrastructure.ReadModel.InstallationReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<string>("CableColor")
                        .HasColumnType("text");

                    b.Property<string>("CableType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConductorCount")
                        .HasColumnType("integer");

                    b.Property<double?>("CorrectionAge")
                        .HasColumnType("double precision");

                    b.Property<string>("CorrectionService")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CrossSection")
                        .HasColumnType("numeric");

                    b.Property<int?>("DepthMm")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GpsSource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Hdop")
                        .HasColumnType("double precision");

                    b.Property<double>("HorizontalAccuracy")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<int>("MeasurementCount")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<int>("PhotoCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("QualityGrade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RtkFixStatus")
                        .HasColumnType("text");

                    b.Property<int?>("SatelliteCount")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status");

                    b.HasIndex("ZoneId");

                    b.ToTable("installations", "documentation_read");
                });

            modelBuilder.Entity("BauDoku.Documentation.Infrastructure.ReadModel.MeasurementReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid");

                    b.Property<double?>("MaxThreshold")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("MinThreshold")
                        .HasColumnType("double precision");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.ToTable("measurements", "documentation_read");
                });

            modelBuilder.Entity("BauDoku.Documentation.Infrastructure.ReadModel.PhotoReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("CorrectionAge")
                        .HasColumnType("double precision");

                    b.Property<string>("CorrectionService")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("GpsSource")
                        .HasColumnType("text");

                    b.Property<double?>("Hdop")
                        .HasColumnType("double precision");

                    b.Property<double?>("HorizontalAccuracy")
                        .HasColumnType("double precision");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PhotoType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RtkFixStatus")
                        .HasColumnType("text");

                    b.Property<int?>("SatelliteCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId");

                    b.ToTable("photos", "documentation_read");
                });

            modelBuilder.Entity("BauDoku.Documentation.Infrastructure.ReadModel.MeasurementReadModel", b =>
                {
                    b.HasOne("BauDoku.Documentation.Infrastructure.ReadModel.InstallationReadModel", "Installation")
                        .WithMany("Measurements")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("BauDoku.Documentation.Infrastructure.ReadModel.PhotoReadModel", b =>
                {
                    b.HasOne("BauDoku.Documentation.Infrastructure.ReadModel.InstallationReadModel", "Installation")
                        .WithMany("Photos")
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Installation");
                });

            modelBuilder.Entity("BauDoku.Documentation.Infrastructure.ReadModel.InstallationReadModel", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
